/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookedRouteImport } from './routes/booked'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as StudioSlugRouteImport } from './routes/studio.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookedRoute = BookedRouteImport.update({
  id: '/booked',
  path: '/booked',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSlugRoute = StudioSlugRouteImport.update({
  id: '/studio/$slug',
  path: '/studio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booked': typeof BookedRoute
  '/discover': typeof DiscoverRoute
  '/b/$slug': typeof BSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/studio/$slug': typeof StudioSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booked': typeof BookedRoute
  '/discover': typeof DiscoverRoute
  '/b/$slug': typeof BSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/studio/$slug': typeof StudioSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booked': typeof BookedRoute
  '/discover': typeof DiscoverRoute
  '/b/$slug': typeof BSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/studio/$slug': typeof StudioSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/booked'
    | '/discover'
    | '/b/$slug'
    | '/book/$slug'
    | '/studio/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/booked'
    | '/discover'
    | '/b/$slug'
    | '/book/$slug'
    | '/studio/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/booked'
    | '/discover'
    | '/b/$slug'
    | '/book/$slug'
    | '/studio/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookedRoute: typeof BookedRoute
  DiscoverRoute: typeof DiscoverRoute
  BSlugRoute: typeof BSlugRoute
  BookSlugRoute: typeof BookSlugRoute
  StudioSlugRoute: typeof StudioSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booked': {
      id: '/booked'
      path: '/booked'
      fullPath: '/booked'
      preLoaderRoute: typeof BookedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$slug': {
      id: '/studio/$slug'
      path: '/studio/$slug'
      fullPath: '/studio/$slug'
      preLoaderRoute: typeof StudioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookedRoute: BookedRoute,
  DiscoverRoute: DiscoverRoute,
  BSlugRoute: BSlugRoute,
  BookSlugRoute: BookSlugRoute,
  StudioSlugRoute: StudioSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
